services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./application/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
    container_name: nginx
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - ./application/:/var/www/html/
      - ./logs/php.log:/var/log/fpm-php.www.log
    container_name: php
    expose:
      - "9000"
  mysql:
    container_name: db
    restart: always
    image: mysql:latest
    platform: linux/x86_64
    command: --init-file /data/application/init.sql
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: berg
      MYSQL_PASS: f1r3l1nkshr1n3
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db/init.sql:/data/application/init.sql
    networks:
      - internal
  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080   
    networks:
      - internal
networks:
  internal:
    driver: bridge